// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `iConstDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace MCS
{
    namespace OHT
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class OHTStatusAlarm
        {
            public const int value = 0;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class OHTStatusWaitingpath
        {
            public const int value = 1;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class OHTStatuswaitingcmd
        {
            public const int value = 2;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class OHTStatusnormalrun
        {
            public const int value = 3;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class OHTStatustargetinpos
        {
            public const int value = 4;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class OHTStatusfoupmoving
        {
            public const int value = 5;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class OHTStatusfoupmoved
        {
            public const int value = 6;
        }
    }

    namespace GUIHUB
    {
        namespace OHT
        {
            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public enum GuiCommand
            {
                PosTime,
                StatusTime,
                GetPosTable,
                FoupHanding,
                PathTest,
                MoveTest,
                FoupTest
            }
        }

        namespace STK
        {
            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public enum Guicommand
            {
                StatusTime
            }
        }
    }
}

namespace MCS
{
    namespace OHT
    {
    }

    namespace GUIHUB
    {
        namespace OHT
        {
        }

        namespace STK
        {
        }
    }
}
