// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `iConstDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace MCS
{
    namespace GuiHub
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public enum GuiCommand
        {
            OhtPosTime,
            OhtStatusTime,
            OhtGetPosTable,
            OhtFoupHanding,
            OhtSetPath,
            OhtMove,
            OhtPathTest,
            OhtMoveTest,
            OhtFoupTest,
            StkStatusTime
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public enum PushData
        {
            upOhtInfo,
            upOhtPos,
            upOhtPosTable,
            upOhtStatus
        }
    }
}

namespace MCS
{
    namespace GuiHub
    {
    }
}
