// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `iConstDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef _____common_iConstDef_h__
#define _____common_iConstDef_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace MCS
{

namespace OHT
{

const ::Ice::Int OHTStatusAlarm = 0;

const ::Ice::Int OHTStatusWaitingpath = 1;

const ::Ice::Int OHTStatuswaitingcmd = 2;

const ::Ice::Int OHTStatusnormalrun = 3;

const ::Ice::Int OHTStatustargetinpos = 4;

const ::Ice::Int OHTStatusfoupmoving = 5;

const ::Ice::Int OHTStatusfoupmoved = 6;

}

enum Fruit
{
    Apple,
    Pear,
    Orange
};

void __write(::IceInternal::BasicStream*, Fruit);
void __read(::IceInternal::BasicStream*, Fruit&);

}

#endif
