// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `iGuiHub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef _____common_iGuiHub_h__
#define _____common_iGuiHub_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace MCS
{

class GuiDataHub;

}

}

namespace MCS
{

class GuiDataHub;
bool operator==(const GuiDataHub&, const GuiDataHub&);
bool operator<(const GuiDataHub&, const GuiDataHub&);

}

namespace IceInternal
{

::Ice::Object* upCast(::MCS::GuiDataHub*);
::IceProxy::Ice::Object* upCast(::IceProxy::MCS::GuiDataHub*);

}

namespace MCS
{

typedef ::IceInternal::Handle< ::MCS::GuiDataHub> GuiDataHubPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::MCS::GuiDataHub> GuiDataHubPrx;

void __read(::IceInternal::BasicStream*, GuiDataHubPrx&);
void __patch__GuiDataHubPtr(void*, ::Ice::ObjectPtr&);

}

namespace MCS
{

class Callback_GuiDataHub_Login_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GuiDataHub_Login_Base> Callback_GuiDataHub_LoginPtr;

class Callback_GuiDataHub_Logout_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GuiDataHub_Logout_Base> Callback_GuiDataHub_LogoutPtr;

class Callback_GuiDataHub_ReadData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GuiDataHub_ReadData_Base> Callback_GuiDataHub_ReadDataPtr;

class Callback_GuiDataHub_WriteData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GuiDataHub_WriteData_Base> Callback_GuiDataHub_WriteDataPtr;

}

namespace IceProxy
{

namespace MCS
{

class GuiDataHub : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Int Login(const ::std::string& user, const ::std::string& pass)
    {
        return Login(user, pass, 0);
    }
    ::Ice::Int Login(const ::std::string& user, const ::std::string& pass, const ::Ice::Context& __ctx)
    {
        return Login(user, pass, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_Login(const ::std::string& user, const ::std::string& pass)
    {
        return begin_Login(user, pass, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Login(const ::std::string& user, const ::std::string& pass, const ::Ice::Context& __ctx)
    {
        return begin_Login(user, pass, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Login(const ::std::string& user, const ::std::string& pass, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Login(user, pass, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Login(const ::std::string& user, const ::std::string& pass, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Login(user, pass, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Login(const ::std::string& user, const ::std::string& pass, const ::MCS::Callback_GuiDataHub_LoginPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Login(user, pass, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Login(const ::std::string& user, const ::std::string& pass, const ::Ice::Context& __ctx, const ::MCS::Callback_GuiDataHub_LoginPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Login(user, pass, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_Login(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int Login(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_Login(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int Logout(::Ice::Int session)
    {
        return Logout(session, 0);
    }
    ::Ice::Int Logout(::Ice::Int session, const ::Ice::Context& __ctx)
    {
        return Logout(session, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_Logout(::Ice::Int session)
    {
        return begin_Logout(session, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Logout(::Ice::Int session, const ::Ice::Context& __ctx)
    {
        return begin_Logout(session, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Logout(::Ice::Int session, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Logout(session, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Logout(::Ice::Int session, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Logout(session, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Logout(::Ice::Int session, const ::MCS::Callback_GuiDataHub_LogoutPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Logout(session, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Logout(::Ice::Int session, const ::Ice::Context& __ctx, const ::MCS::Callback_GuiDataHub_LogoutPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Logout(session, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_Logout(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int Logout(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_Logout(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string ReadData(const ::std::string& Tag, ::Ice::Int session)
    {
        return ReadData(Tag, session, 0);
    }
    ::std::string ReadData(const ::std::string& Tag, ::Ice::Int session, const ::Ice::Context& __ctx)
    {
        return ReadData(Tag, session, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_ReadData(const ::std::string& Tag, ::Ice::Int session)
    {
        return begin_ReadData(Tag, session, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ReadData(const ::std::string& Tag, ::Ice::Int session, const ::Ice::Context& __ctx)
    {
        return begin_ReadData(Tag, session, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ReadData(const ::std::string& Tag, ::Ice::Int session, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReadData(Tag, session, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ReadData(const ::std::string& Tag, ::Ice::Int session, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReadData(Tag, session, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ReadData(const ::std::string& Tag, ::Ice::Int session, const ::MCS::Callback_GuiDataHub_ReadDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReadData(Tag, session, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ReadData(const ::std::string& Tag, ::Ice::Int session, const ::Ice::Context& __ctx, const ::MCS::Callback_GuiDataHub_ReadDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ReadData(Tag, session, &__ctx, __del, __cookie);
    }

    ::std::string end_ReadData(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string ReadData(const ::std::string&, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_ReadData(const ::std::string&, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session)
    {
        return WriteData(Tag, Val, session, 0);
    }
    ::Ice::Int WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session, const ::Ice::Context& __ctx)
    {
        return WriteData(Tag, Val, session, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session)
    {
        return begin_WriteData(Tag, Val, session, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session, const ::Ice::Context& __ctx)
    {
        return begin_WriteData(Tag, Val, session, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_WriteData(Tag, Val, session, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_WriteData(Tag, Val, session, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session, const ::MCS::Callback_GuiDataHub_WriteDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_WriteData(Tag, Val, session, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_WriteData(const ::std::string& Tag, const ::std::string& Val, ::Ice::Int session, const ::Ice::Context& __ctx, const ::MCS::Callback_GuiDataHub_WriteDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_WriteData(Tag, Val, session, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_WriteData(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int WriteData(const ::std::string&, const ::std::string&, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_WriteData(const ::std::string&, const ::std::string&, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GuiDataHub> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GuiDataHub*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<GuiDataHub*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace MCS
{

class GuiDataHub : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Ice::Int Login(const ::std::string&, const ::std::string&, const ::Ice::Context*) = 0;

    virtual ::Ice::Int Logout(::Ice::Int, const ::Ice::Context*) = 0;

    virtual ::std::string ReadData(const ::std::string&, ::Ice::Int, const ::Ice::Context*) = 0;

    virtual ::Ice::Int WriteData(const ::std::string&, const ::std::string&, ::Ice::Int, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace MCS
{

class GuiDataHub : virtual public ::IceDelegate::MCS::GuiDataHub,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Ice::Int Login(const ::std::string&, const ::std::string&, const ::Ice::Context*);

    virtual ::Ice::Int Logout(::Ice::Int, const ::Ice::Context*);

    virtual ::std::string ReadData(const ::std::string&, ::Ice::Int, const ::Ice::Context*);

    virtual ::Ice::Int WriteData(const ::std::string&, const ::std::string&, ::Ice::Int, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace MCS
{

class GuiDataHub : virtual public ::IceDelegate::MCS::GuiDataHub,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Ice::Int Login(const ::std::string&, const ::std::string&, const ::Ice::Context*);

    virtual ::Ice::Int Logout(::Ice::Int, const ::Ice::Context*);

    virtual ::std::string ReadData(const ::std::string&, ::Ice::Int, const ::Ice::Context*);

    virtual ::Ice::Int WriteData(const ::std::string&, const ::std::string&, ::Ice::Int, const ::Ice::Context*);
};

}

}

namespace MCS
{

class GuiDataHub : virtual public ::Ice::Object
{
public:

    typedef GuiDataHubPrx ProxyType;
    typedef GuiDataHubPtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::Int Login(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___Login(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int Logout(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___Logout(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string ReadData(const ::std::string&, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___ReadData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int WriteData(const ::std::string&, const ::std::string&, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___WriteData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const GuiDataHub& l, const GuiDataHub& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const GuiDataHub& l, const GuiDataHub& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace MCS
{

template<class T>
class CallbackNC_GuiDataHub_Login : public Callback_GuiDataHub_Login_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_GuiDataHub_Login(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_Login(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GuiDataHub_LoginPtr
newCallback_GuiDataHub_Login(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_Login<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GuiDataHub_LoginPtr
newCallback_GuiDataHub_Login(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_Login<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GuiDataHub_Login : public Callback_GuiDataHub_Login_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_GuiDataHub_Login(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_Login(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GuiDataHub_LoginPtr
newCallback_GuiDataHub_Login(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_Login<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GuiDataHub_LoginPtr
newCallback_GuiDataHub_Login(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_Login<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GuiDataHub_Logout : public Callback_GuiDataHub_Logout_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_GuiDataHub_Logout(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_Logout(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GuiDataHub_LogoutPtr
newCallback_GuiDataHub_Logout(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_Logout<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GuiDataHub_LogoutPtr
newCallback_GuiDataHub_Logout(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_Logout<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GuiDataHub_Logout : public Callback_GuiDataHub_Logout_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_GuiDataHub_Logout(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_Logout(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GuiDataHub_LogoutPtr
newCallback_GuiDataHub_Logout(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_Logout<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GuiDataHub_LogoutPtr
newCallback_GuiDataHub_Logout(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_Logout<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GuiDataHub_ReadData : public Callback_GuiDataHub_ReadData_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_GuiDataHub_ReadData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_ReadData(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GuiDataHub_ReadDataPtr
newCallback_GuiDataHub_ReadData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_ReadData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GuiDataHub_ReadDataPtr
newCallback_GuiDataHub_ReadData(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_ReadData<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GuiDataHub_ReadData : public Callback_GuiDataHub_ReadData_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_GuiDataHub_ReadData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_ReadData(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GuiDataHub_ReadDataPtr
newCallback_GuiDataHub_ReadData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_ReadData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GuiDataHub_ReadDataPtr
newCallback_GuiDataHub_ReadData(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_ReadData<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GuiDataHub_WriteData : public Callback_GuiDataHub_WriteData_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_GuiDataHub_WriteData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_WriteData(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GuiDataHub_WriteDataPtr
newCallback_GuiDataHub_WriteData(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_WriteData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GuiDataHub_WriteDataPtr
newCallback_GuiDataHub_WriteData(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GuiDataHub_WriteData<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GuiDataHub_WriteData : public Callback_GuiDataHub_WriteData_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_GuiDataHub_WriteData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MCS::GuiDataHubPrx __proxy = ::MCS::GuiDataHubPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_WriteData(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GuiDataHub_WriteDataPtr
newCallback_GuiDataHub_WriteData(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_WriteData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GuiDataHub_WriteDataPtr
newCallback_GuiDataHub_WriteData(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GuiDataHub_WriteData<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
