// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `iMesLink.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace MCS
{
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial class LocFoup : _System.ICloneable
    {
        #region Slice data members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public int nDevID;

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public int nLocType;

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public string sStatus;

        #endregion

        #region Constructors

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public LocFoup()
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public LocFoup(int nDevID, int nLocType, string sStatus)
        {
            this.nDevID = nDevID;
            this.nLocType = nLocType;
            this.sStatus = sStatus;
        }

        #endregion

        #region ICloneable members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public object Clone()
        {
            return MemberwiseClone();
        }

        #endregion

        #region Object members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public override int GetHashCode()
        {
            int h__ = 0;
            h__ = 5 * h__ + nDevID.GetHashCode();
            h__ = 5 * h__ + nLocType.GetHashCode();
            if(sStatus != null)
            {
                h__ = 5 * h__ + sStatus.GetHashCode();
            }
            return h__;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public override bool Equals(object other__)
        {
            if(object.ReferenceEquals(this, other__))
            {
                return true;
            }
            if(other__ == null)
            {
                return false;
            }
            if(GetType() != other__.GetType())
            {
                return false;
            }
            LocFoup o__ = (LocFoup)other__;
            if(!nDevID.Equals(o__.nDevID))
            {
                return false;
            }
            if(!nLocType.Equals(o__.nLocType))
            {
                return false;
            }
            if(sStatus == null)
            {
                if(o__.sStatus != null)
                {
                    return false;
                }
            }
            else
            {
                if(!sStatus.Equals(o__.sStatus))
                {
                    return false;
                }
            }
            return true;
        }

        #endregion

        #region Comparison members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public static bool operator==(LocFoup lhs__, LocFoup rhs__)
        {
            return Equals(lhs__, rhs__);
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public static bool operator!=(LocFoup lhs__, LocFoup rhs__)
        {
            return !Equals(lhs__, rhs__);
        }

        #endregion

        #region Marshalling support

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public void write__(IceInternal.BasicStream os__)
        {
            os__.writeInt(nDevID);
            os__.writeInt(nLocType);
            os__.writeString(sStatus);
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public void read__(IceInternal.BasicStream is__)
        {
            nDevID = is__.readInt();
            nLocType = is__.readInt();
            sStatus = is__.readString();
        }

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface MESLink : Ice.Object, MESLinkOperations_, MESLinkOperationsNC_
    {
    }
}

namespace MCS
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public delegate void Callback_MESLink_PlaceFoup(int ret__);

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public delegate void Callback_MESLink_PickFoup(int ret__);

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public delegate void Callback_MESLink_GetFoup(MCS.LocFoup ret__);
}

namespace MCS
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public interface MESLinkPrx : Ice.ObjectPrx
    {
        int PlaceFoup(int foupBarCode, int DevID, int nLocType);
        int PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<MCS.Callback_MESLink_PlaceFoup> begin_PlaceFoup(int foupBarCode, int DevID, int nLocType);
        Ice.AsyncResult<MCS.Callback_MESLink_PlaceFoup> begin_PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_PlaceFoup(int foupBarCode, int DevID, int nLocType, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        int end_PlaceFoup(Ice.AsyncResult r__);

        int PickFoup(int foupBarCode, int DevID, int nLocType);
        int PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<MCS.Callback_MESLink_PickFoup> begin_PickFoup(int foupBarCode, int DevID, int nLocType);
        Ice.AsyncResult<MCS.Callback_MESLink_PickFoup> begin_PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_PickFoup(int foupBarCode, int DevID, int nLocType, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        int end_PickFoup(Ice.AsyncResult r__);

        MCS.LocFoup GetFoup(int foupBarCode);
        MCS.LocFoup GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<MCS.Callback_MESLink_GetFoup> begin_GetFoup(int foupBarCode);
        Ice.AsyncResult<MCS.Callback_MESLink_GetFoup> begin_GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_GetFoup(int foupBarCode, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        MCS.LocFoup end_GetFoup(Ice.AsyncResult r__);
    }
}

namespace MCS
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public interface MESLinkOperations_
    {
        int PlaceFoup(int foupBarCode, int DevID, int nLocType, Ice.Current current__);

        int PickFoup(int foupBarCode, int DevID, int nLocType, Ice.Current current__);

        MCS.LocFoup GetFoup(int foupBarCode, Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public interface MESLinkOperationsNC_
    {
        int PlaceFoup(int foupBarCode, int DevID, int nLocType);

        int PickFoup(int foupBarCode, int DevID, int nLocType);

        MCS.LocFoup GetFoup(int foupBarCode);
    }
}

namespace MCS
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public sealed class MESLinkPrxHelper : Ice.ObjectPrxHelperBase, MESLinkPrx
    {
        #region Synchronous operations

        public MCS.LocFoup GetFoup(int foupBarCode)
        {
            return GetFoup(foupBarCode, null, false);
        }

        public MCS.LocFoup GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            return GetFoup(foupBarCode, context__, true);
        }

        private MCS.LocFoup GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitContext__)
        {
            if(explicitContext__ && context__ == null)
            {
                context__ = emptyContext_;
            }
            int cnt__ = 0;
            while(true)
            {
                Ice.ObjectDel_ delBase__ = null;
                try
                {
                    checkTwowayOnly__("GetFoup");
                    delBase__ = getDelegate__(false);
                    MESLinkDel_ del__ = (MESLinkDel_)delBase__;
                    return del__.GetFoup(foupBarCode, context__);
                }
                catch(IceInternal.LocalExceptionWrapper ex__)
                {
                    handleExceptionWrapperRelaxed__(delBase__, ex__, true, ref cnt__);
                }
                catch(Ice.LocalException ex__)
                {
                    handleException__(delBase__, ex__, true, ref cnt__);
                }
            }
        }

        public int PickFoup(int foupBarCode, int DevID, int nLocType)
        {
            return PickFoup(foupBarCode, DevID, nLocType, null, false);
        }

        public int PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            return PickFoup(foupBarCode, DevID, nLocType, context__, true);
        }

        private int PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitContext__)
        {
            if(explicitContext__ && context__ == null)
            {
                context__ = emptyContext_;
            }
            int cnt__ = 0;
            while(true)
            {
                Ice.ObjectDel_ delBase__ = null;
                try
                {
                    checkTwowayOnly__("PickFoup");
                    delBase__ = getDelegate__(false);
                    MESLinkDel_ del__ = (MESLinkDel_)delBase__;
                    return del__.PickFoup(foupBarCode, DevID, nLocType, context__);
                }
                catch(IceInternal.LocalExceptionWrapper ex__)
                {
                    handleExceptionWrapperRelaxed__(delBase__, ex__, true, ref cnt__);
                }
                catch(Ice.LocalException ex__)
                {
                    handleException__(delBase__, ex__, true, ref cnt__);
                }
            }
        }

        public int PlaceFoup(int foupBarCode, int DevID, int nLocType)
        {
            return PlaceFoup(foupBarCode, DevID, nLocType, null, false);
        }

        public int PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            return PlaceFoup(foupBarCode, DevID, nLocType, context__, true);
        }

        private int PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitContext__)
        {
            if(explicitContext__ && context__ == null)
            {
                context__ = emptyContext_;
            }
            int cnt__ = 0;
            while(true)
            {
                Ice.ObjectDel_ delBase__ = null;
                try
                {
                    checkTwowayOnly__("PlaceFoup");
                    delBase__ = getDelegate__(false);
                    MESLinkDel_ del__ = (MESLinkDel_)delBase__;
                    return del__.PlaceFoup(foupBarCode, DevID, nLocType, context__);
                }
                catch(IceInternal.LocalExceptionWrapper ex__)
                {
                    handleExceptionWrapperRelaxed__(delBase__, ex__, true, ref cnt__);
                }
                catch(Ice.LocalException ex__)
                {
                    handleException__(delBase__, ex__, true, ref cnt__);
                }
            }
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<MCS.Callback_MESLink_GetFoup> begin_GetFoup(int foupBarCode)
        {
            return begin_GetFoup(foupBarCode, null, false, null, null);
        }

        public Ice.AsyncResult<MCS.Callback_MESLink_GetFoup> begin_GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_GetFoup(foupBarCode, ctx__, true, null, null);
        }

        public Ice.AsyncResult begin_GetFoup(int foupBarCode, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_GetFoup(foupBarCode, null, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_GetFoup(foupBarCode, ctx__, true, cb__, cookie__);
        }

        private const string __GetFoup_name = "GetFoup";

        public MCS.LocFoup end_GetFoup(Ice.AsyncResult r__)
        {
            IceInternal.OutgoingAsync outAsync__ = (IceInternal.OutgoingAsync)r__;
            IceInternal.OutgoingAsync.check__(outAsync__, this, __GetFoup_name);
            if(!outAsync__.wait__())
            {
                try
                {
                    outAsync__.throwUserException__();
                }
                catch(Ice.UserException ex__)
                {
                    throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                }
            }
            MCS.LocFoup ret__;
            IceInternal.BasicStream is__ = outAsync__.istr__;
            is__.startReadEncaps();
            ret__ = null;
            if(ret__ == null)
            {
                ret__ = new MCS.LocFoup();
            }
            ret__.read__(is__);
            is__.endReadEncaps();
            return ret__;
        }

        private Ice.AsyncResult<MCS.Callback_MESLink_GetFoup> begin_GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, Ice.AsyncCallback cb__, object cookie__)
        {
            checkAsyncTwowayOnly__(__GetFoup_name);
            IceInternal.TwowayOutgoingAsync<MCS.Callback_MESLink_GetFoup> result__ =  new IceInternal.TwowayOutgoingAsync<MCS.Callback_MESLink_GetFoup>(this, __GetFoup_name, GetFoup_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare__(__GetFoup_name, Ice.OperationMode.Idempotent, ctx__, explicitContext__);
                IceInternal.BasicStream os__ = result__.ostr__;
                os__.writeInt(foupBarCode);
                os__.endWriteEncaps();
                result__.send__(true);
            }
            catch(Ice.LocalException ex__)
            {
                result__.exceptionAsync__(ex__);
            }
            return result__;
        }

        private void GetFoup_completed__(Ice.AsyncResult r__, MCS.Callback_MESLink_GetFoup cb__, Ice.ExceptionCallback excb__)
        {
            MCS.LocFoup ret__;
            try
            {
                ret__ = end_GetFoup(r__);
            }
            catch(Ice.Exception ex__)
            {
                if(excb__ != null)
                {
                    excb__(ex__);
                }
                return;
            }
            if(cb__ != null)
            {
                cb__(ret__);
            }
        }

        public Ice.AsyncResult<MCS.Callback_MESLink_PickFoup> begin_PickFoup(int foupBarCode, int DevID, int nLocType)
        {
            return begin_PickFoup(foupBarCode, DevID, nLocType, null, false, null, null);
        }

        public Ice.AsyncResult<MCS.Callback_MESLink_PickFoup> begin_PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_PickFoup(foupBarCode, DevID, nLocType, ctx__, true, null, null);
        }

        public Ice.AsyncResult begin_PickFoup(int foupBarCode, int DevID, int nLocType, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_PickFoup(foupBarCode, DevID, nLocType, null, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_PickFoup(foupBarCode, DevID, nLocType, ctx__, true, cb__, cookie__);
        }

        private const string __PickFoup_name = "PickFoup";

        public int end_PickFoup(Ice.AsyncResult r__)
        {
            IceInternal.OutgoingAsync outAsync__ = (IceInternal.OutgoingAsync)r__;
            IceInternal.OutgoingAsync.check__(outAsync__, this, __PickFoup_name);
            if(!outAsync__.wait__())
            {
                try
                {
                    outAsync__.throwUserException__();
                }
                catch(Ice.UserException ex__)
                {
                    throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                }
            }
            int ret__;
            IceInternal.BasicStream is__ = outAsync__.istr__;
            is__.startReadEncaps();
            ret__ = is__.readInt();
            is__.endReadEncaps();
            return ret__;
        }

        private Ice.AsyncResult<MCS.Callback_MESLink_PickFoup> begin_PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, Ice.AsyncCallback cb__, object cookie__)
        {
            checkAsyncTwowayOnly__(__PickFoup_name);
            IceInternal.TwowayOutgoingAsync<MCS.Callback_MESLink_PickFoup> result__ =  new IceInternal.TwowayOutgoingAsync<MCS.Callback_MESLink_PickFoup>(this, __PickFoup_name, PickFoup_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare__(__PickFoup_name, Ice.OperationMode.Idempotent, ctx__, explicitContext__);
                IceInternal.BasicStream os__ = result__.ostr__;
                os__.writeInt(foupBarCode);
                os__.writeInt(DevID);
                os__.writeInt(nLocType);
                os__.endWriteEncaps();
                result__.send__(true);
            }
            catch(Ice.LocalException ex__)
            {
                result__.exceptionAsync__(ex__);
            }
            return result__;
        }

        private void PickFoup_completed__(Ice.AsyncResult r__, MCS.Callback_MESLink_PickFoup cb__, Ice.ExceptionCallback excb__)
        {
            int ret__;
            try
            {
                ret__ = end_PickFoup(r__);
            }
            catch(Ice.Exception ex__)
            {
                if(excb__ != null)
                {
                    excb__(ex__);
                }
                return;
            }
            if(cb__ != null)
            {
                cb__(ret__);
            }
        }

        public Ice.AsyncResult<MCS.Callback_MESLink_PlaceFoup> begin_PlaceFoup(int foupBarCode, int DevID, int nLocType)
        {
            return begin_PlaceFoup(foupBarCode, DevID, nLocType, null, false, null, null);
        }

        public Ice.AsyncResult<MCS.Callback_MESLink_PlaceFoup> begin_PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_PlaceFoup(foupBarCode, DevID, nLocType, ctx__, true, null, null);
        }

        public Ice.AsyncResult begin_PlaceFoup(int foupBarCode, int DevID, int nLocType, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_PlaceFoup(foupBarCode, DevID, nLocType, null, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_PlaceFoup(foupBarCode, DevID, nLocType, ctx__, true, cb__, cookie__);
        }

        private const string __PlaceFoup_name = "PlaceFoup";

        public int end_PlaceFoup(Ice.AsyncResult r__)
        {
            IceInternal.OutgoingAsync outAsync__ = (IceInternal.OutgoingAsync)r__;
            IceInternal.OutgoingAsync.check__(outAsync__, this, __PlaceFoup_name);
            if(!outAsync__.wait__())
            {
                try
                {
                    outAsync__.throwUserException__();
                }
                catch(Ice.UserException ex__)
                {
                    throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                }
            }
            int ret__;
            IceInternal.BasicStream is__ = outAsync__.istr__;
            is__.startReadEncaps();
            ret__ = is__.readInt();
            is__.endReadEncaps();
            return ret__;
        }

        private Ice.AsyncResult<MCS.Callback_MESLink_PlaceFoup> begin_PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, Ice.AsyncCallback cb__, object cookie__)
        {
            checkAsyncTwowayOnly__(__PlaceFoup_name);
            IceInternal.TwowayOutgoingAsync<MCS.Callback_MESLink_PlaceFoup> result__ =  new IceInternal.TwowayOutgoingAsync<MCS.Callback_MESLink_PlaceFoup>(this, __PlaceFoup_name, PlaceFoup_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare__(__PlaceFoup_name, Ice.OperationMode.Idempotent, ctx__, explicitContext__);
                IceInternal.BasicStream os__ = result__.ostr__;
                os__.writeInt(foupBarCode);
                os__.writeInt(DevID);
                os__.writeInt(nLocType);
                os__.endWriteEncaps();
                result__.send__(true);
            }
            catch(Ice.LocalException ex__)
            {
                result__.exceptionAsync__(ex__);
            }
            return result__;
        }

        private void PlaceFoup_completed__(Ice.AsyncResult r__, MCS.Callback_MESLink_PlaceFoup cb__, Ice.ExceptionCallback excb__)
        {
            int ret__;
            try
            {
                ret__ = end_PlaceFoup(r__);
            }
            catch(Ice.Exception ex__)
            {
                if(excb__ != null)
                {
                    excb__(ex__);
                }
                return;
            }
            if(cb__ != null)
            {
                cb__(ret__);
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static MESLinkPrx checkedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            MESLinkPrx r = b as MESLinkPrx;
            if((r == null) && b.ice_isA(ice_staticId()))
            {
                MESLinkPrxHelper h = new MESLinkPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static MESLinkPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            MESLinkPrx r = b as MESLinkPrx;
            if((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                MESLinkPrxHelper h = new MESLinkPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static MESLinkPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId()))
                {
                    MESLinkPrxHelper h = new MESLinkPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static MESLinkPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId(), ctx))
                {
                    MESLinkPrxHelper h = new MESLinkPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static MESLinkPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            MESLinkPrx r = b as MESLinkPrx;
            if(r == null)
            {
                MESLinkPrxHelper h = new MESLinkPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static MESLinkPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            MESLinkPrxHelper h = new MESLinkPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::Ice::Object",
            "::MCS::MESLink"
        };

        public static string ice_staticId()
        {
            return ids__[1];
        }

        #endregion

        #region Marshaling support

        protected override Ice.ObjectDelM_ createDelegateM__()
        {
            return new MESLinkDelM_();
        }

        protected override Ice.ObjectDelD_ createDelegateD__()
        {
            return new MESLinkDelD_();
        }

        public static void write__(IceInternal.BasicStream os__, MESLinkPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static MESLinkPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if(proxy != null)
            {
                MESLinkPrxHelper result = new MESLinkPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }
}

namespace MCS
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public interface MESLinkDel_ : Ice.ObjectDel_
    {
        int PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__);

        int PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__);

        MCS.LocFoup GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> context__);
    }
}

namespace MCS
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public sealed class MESLinkDelM_ : Ice.ObjectDelM_, MESLinkDel_
    {
        public MCS.LocFoup GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            IceInternal.Outgoing og__ = handler__.getOutgoing("GetFoup", Ice.OperationMode.Idempotent, context__);
            try
            {
                try
                {
                    IceInternal.BasicStream os__ = og__.ostr();
                    os__.writeInt(foupBarCode);
                }
                catch(Ice.LocalException ex__)
                {
                    og__.abort(ex__);
                }
                bool ok__ = og__.invoke();
                try
                {
                    if(!ok__)
                    {
                        try
                        {
                            og__.throwUserException();
                        }
                        catch(Ice.UserException ex__)
                        {
                            throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                        }
                    }
                    IceInternal.BasicStream is__ = og__.istr();
                    is__.startReadEncaps();
                    MCS.LocFoup ret__;
                    ret__ = null;
                    if(ret__ == null)
                    {
                        ret__ = new MCS.LocFoup();
                    }
                    ret__.read__(is__);
                    is__.endReadEncaps();
                    return ret__;
                }
                catch(Ice.LocalException ex__)
                {
                    throw new IceInternal.LocalExceptionWrapper(ex__, false);
                }
            }
            finally
            {
                handler__.reclaimOutgoing(og__);
            }
        }

        public int PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            IceInternal.Outgoing og__ = handler__.getOutgoing("PickFoup", Ice.OperationMode.Idempotent, context__);
            try
            {
                try
                {
                    IceInternal.BasicStream os__ = og__.ostr();
                    os__.writeInt(foupBarCode);
                    os__.writeInt(DevID);
                    os__.writeInt(nLocType);
                }
                catch(Ice.LocalException ex__)
                {
                    og__.abort(ex__);
                }
                bool ok__ = og__.invoke();
                try
                {
                    if(!ok__)
                    {
                        try
                        {
                            og__.throwUserException();
                        }
                        catch(Ice.UserException ex__)
                        {
                            throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                        }
                    }
                    IceInternal.BasicStream is__ = og__.istr();
                    is__.startReadEncaps();
                    int ret__;
                    ret__ = is__.readInt();
                    is__.endReadEncaps();
                    return ret__;
                }
                catch(Ice.LocalException ex__)
                {
                    throw new IceInternal.LocalExceptionWrapper(ex__, false);
                }
            }
            finally
            {
                handler__.reclaimOutgoing(og__);
            }
        }

        public int PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            IceInternal.Outgoing og__ = handler__.getOutgoing("PlaceFoup", Ice.OperationMode.Idempotent, context__);
            try
            {
                try
                {
                    IceInternal.BasicStream os__ = og__.ostr();
                    os__.writeInt(foupBarCode);
                    os__.writeInt(DevID);
                    os__.writeInt(nLocType);
                }
                catch(Ice.LocalException ex__)
                {
                    og__.abort(ex__);
                }
                bool ok__ = og__.invoke();
                try
                {
                    if(!ok__)
                    {
                        try
                        {
                            og__.throwUserException();
                        }
                        catch(Ice.UserException ex__)
                        {
                            throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                        }
                    }
                    IceInternal.BasicStream is__ = og__.istr();
                    is__.startReadEncaps();
                    int ret__;
                    ret__ = is__.readInt();
                    is__.endReadEncaps();
                    return ret__;
                }
                catch(Ice.LocalException ex__)
                {
                    throw new IceInternal.LocalExceptionWrapper(ex__, false);
                }
            }
            finally
            {
                handler__.reclaimOutgoing(og__);
            }
        }
    }
}

namespace MCS
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public sealed class MESLinkDelD_ : Ice.ObjectDelD_, MESLinkDel_
    {
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031")]
        public MCS.LocFoup GetFoup(int foupBarCode, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            Ice.Current current__ = new Ice.Current();
            initCurrent__(ref current__, "GetFoup", Ice.OperationMode.Idempotent, context__);
            MCS.LocFoup result__ = new MCS.LocFoup();
            IceInternal.Direct.RunDelegate run__ = delegate(Ice.Object obj__)
            {
                MESLink servant__ = null;
                try
                {
                    servant__ = (MESLink)obj__;
                }
                catch(_System.InvalidCastException)
                {
                    throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
                }
                result__ = servant__.GetFoup(foupBarCode, current__);
                return Ice.DispatchStatus.DispatchOK;
            };
            IceInternal.Direct direct__ = null;
            try
            {
                direct__ = new IceInternal.Direct(current__, run__);
                try
                {
                    Ice.DispatchStatus status__ = direct__.servant().collocDispatch__(direct__);
                    _System.Diagnostics.Debug.Assert(status__ == Ice.DispatchStatus.DispatchOK);
                }
                finally
                {
                    direct__.destroy();
                }
            }
            catch(Ice.SystemException)
            {
                throw;
            }
            catch(_System.Exception ex__)
            {
                IceInternal.LocalExceptionWrapper.throwWrapper(ex__);
            }
            return result__;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031")]
        public int PickFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            Ice.Current current__ = new Ice.Current();
            initCurrent__(ref current__, "PickFoup", Ice.OperationMode.Idempotent, context__);
            int result__ = 0;
            IceInternal.Direct.RunDelegate run__ = delegate(Ice.Object obj__)
            {
                MESLink servant__ = null;
                try
                {
                    servant__ = (MESLink)obj__;
                }
                catch(_System.InvalidCastException)
                {
                    throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
                }
                result__ = servant__.PickFoup(foupBarCode, DevID, nLocType, current__);
                return Ice.DispatchStatus.DispatchOK;
            };
            IceInternal.Direct direct__ = null;
            try
            {
                direct__ = new IceInternal.Direct(current__, run__);
                try
                {
                    Ice.DispatchStatus status__ = direct__.servant().collocDispatch__(direct__);
                    _System.Diagnostics.Debug.Assert(status__ == Ice.DispatchStatus.DispatchOK);
                }
                finally
                {
                    direct__.destroy();
                }
            }
            catch(Ice.SystemException)
            {
                throw;
            }
            catch(_System.Exception ex__)
            {
                IceInternal.LocalExceptionWrapper.throwWrapper(ex__);
            }
            return result__;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031")]
        public int PlaceFoup(int foupBarCode, int DevID, int nLocType, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            Ice.Current current__ = new Ice.Current();
            initCurrent__(ref current__, "PlaceFoup", Ice.OperationMode.Idempotent, context__);
            int result__ = 0;
            IceInternal.Direct.RunDelegate run__ = delegate(Ice.Object obj__)
            {
                MESLink servant__ = null;
                try
                {
                    servant__ = (MESLink)obj__;
                }
                catch(_System.InvalidCastException)
                {
                    throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
                }
                result__ = servant__.PlaceFoup(foupBarCode, DevID, nLocType, current__);
                return Ice.DispatchStatus.DispatchOK;
            };
            IceInternal.Direct direct__ = null;
            try
            {
                direct__ = new IceInternal.Direct(current__, run__);
                try
                {
                    Ice.DispatchStatus status__ = direct__.servant().collocDispatch__(direct__);
                    _System.Diagnostics.Debug.Assert(status__ == Ice.DispatchStatus.DispatchOK);
                }
                finally
                {
                    direct__.destroy();
                }
            }
            catch(Ice.SystemException)
            {
                throw;
            }
            catch(_System.Exception ex__)
            {
                IceInternal.LocalExceptionWrapper.throwWrapper(ex__);
            }
            return result__;
        }
    }
}

namespace MCS
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
    public abstract class MESLinkDisp_ : Ice.ObjectImpl, MESLink
    {
        #region Slice operations

        public int PlaceFoup(int foupBarCode, int DevID, int nLocType)
        {
            return PlaceFoup(foupBarCode, DevID, nLocType, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract int PlaceFoup(int foupBarCode, int DevID, int nLocType, Ice.Current current__);

        public int PickFoup(int foupBarCode, int DevID, int nLocType)
        {
            return PickFoup(foupBarCode, DevID, nLocType, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract int PickFoup(int foupBarCode, int DevID, int nLocType, Ice.Current current__);

        public MCS.LocFoup GetFoup(int foupBarCode)
        {
            return GetFoup(foupBarCode, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract MCS.LocFoup GetFoup(int foupBarCode, Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ = 
        {
            "::Ice::Object",
            "::MCS::MESLink"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[1];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[1];
        }

        public static new string ice_staticId()
        {
            return ids__[1];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus PlaceFoup___(MESLink obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            checkMode__(Ice.OperationMode.Idempotent, current__.mode);
            IceInternal.BasicStream is__ = inS__.istr();
            is__.startReadEncaps();
            int foupBarCode;
            foupBarCode = is__.readInt();
            int DevID;
            DevID = is__.readInt();
            int nLocType;
            nLocType = is__.readInt();
            is__.endReadEncaps();
            IceInternal.BasicStream os__ = inS__.ostr();
            int ret__ = obj__.PlaceFoup(foupBarCode, DevID, nLocType, current__);
            os__.writeInt(ret__);
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus PickFoup___(MESLink obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            checkMode__(Ice.OperationMode.Idempotent, current__.mode);
            IceInternal.BasicStream is__ = inS__.istr();
            is__.startReadEncaps();
            int foupBarCode;
            foupBarCode = is__.readInt();
            int DevID;
            DevID = is__.readInt();
            int nLocType;
            nLocType = is__.readInt();
            is__.endReadEncaps();
            IceInternal.BasicStream os__ = inS__.ostr();
            int ret__ = obj__.PickFoup(foupBarCode, DevID, nLocType, current__);
            os__.writeInt(ret__);
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus GetFoup___(MESLink obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            checkMode__(Ice.OperationMode.Idempotent, current__.mode);
            IceInternal.BasicStream is__ = inS__.istr();
            is__.startReadEncaps();
            int foupBarCode;
            foupBarCode = is__.readInt();
            is__.endReadEncaps();
            IceInternal.BasicStream os__ = inS__.ostr();
            MCS.LocFoup ret__ = obj__.GetFoup(foupBarCode, current__);
            if(ret__ == null)
            {
                MCS.LocFoup tmp__ = new MCS.LocFoup();
                tmp__.write__(os__);
            }
            else
            {
                ret__.write__(os__);
            }
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "GetFoup",
            "PickFoup",
            "PlaceFoup",
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if(pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch(pos)
            {
                case 0:
                {
                    return GetFoup___(this, inS__, current__);
                }
                case 1:
                {
                    return PickFoup___(this, inS__, current__);
                }
                case 2:
                {
                    return PlaceFoup___(this, inS__, current__);
                }
                case 3:
                {
                    return ice_id___(this, inS__, current__);
                }
                case 4:
                {
                    return ice_ids___(this, inS__, current__);
                }
                case 5:
                {
                    return ice_isA___(this, inS__, current__);
                }
                case 6:
                {
                    return ice_ping___(this, inS__, current__);
                }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        public override void write__(IceInternal.BasicStream os__)
        {
            os__.writeTypeId(ice_staticId());
            os__.startWriteSlice();
            os__.endWriteSlice();
            base.write__(os__);
        }

        public override void read__(IceInternal.BasicStream is__, bool rid__)
        {
            if(rid__)
            {
                /* string myId = */ is__.readTypeId();
            }
            is__.startReadSlice();
            is__.endReadSlice();
            base.read__(is__, true);
        }

        public override void write__(Ice.OutputStream outS__)
        {
            Ice.MarshalException ex = new Ice.MarshalException();
            ex.reason = "type MCS::MESLink was not generated with stream support";
            throw ex;
        }

        public override void read__(Ice.InputStream inS__, bool rid__)
        {
            Ice.MarshalException ex = new Ice.MarshalException();
            ex.reason = "type MCS::MESLink was not generated with stream support";
            throw ex;
        }

        #endregion
    }
}
